#!/bin/sh -e

#For debugging uncomment these two lines
set -x
echo $*

APP_NAME=snomed-refset-service

supervisorctl update $APP_NAME 2>&1 >/dev/null
supervisorctl start $APP_NAME 2>&1 >/dev/null