
# Spring Properties
spring.application.name=ihtsdo-refset-service
#spring.application.profiles.include=
spring.jackson.serialization.INDENT_OUTPUT=true
spring.cache.jcache.config=classpath:ehcache.xml
management.endpoints.web.exposure.include=heapdump,liquibase,loggers,prometheus,threaddump,info,metrics,health

# Logging Properties
logging.level.org.springframework=WARN
logging.level.org.ihtsdo.refsetservice=INFO
logging.level.org.springframework.data.elasticsearch.core=INFO

# Server Properties
server.port=${SERVER_PORT:8080}
server.servlet.context-path=/
server.servlet.session.persistent=false

# Application Properties - TBD
app.metrics.enabled=false
app.service.elasticsearch.host=${ES_HOST:http://localhost:9200}
app.service.elasticsearch.user=${ES_USER:elastic}
app.service.elasticsearch.password=${ES_PASSWORD:changeme}

