
# Spring configuration
spring.application.name=ihtsdo-refset-service
spring.jackson.serialization.INDENT_OUTPUT=true
spring.cache.jcache.config=classpath:ehcache.xml
management.endpoints.web.exposure.include=heapdump,liquibase,loggers,prometheus,threaddump,info,metrics,health
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

# Server Properties
server.port=${SERVER_PORT:8080}
server.servlet.context-path=/
server.servlet.session.persistent=false

# Application Properties
deploy.title=IHTSDO Refset Service Application
app.metrics.enabled=false
app.service.elasticsearch.host=${ES_HOST:http://localhost:9200}
app.service.elasticsearch.user=${ES_USER:elastic}
app.service.elasticsearch.password=${ES_PASSWORD:changeme}
app.entity_packages=org.ihtsdo.refsetservice.model

# Snowstorm Properties
snowstorm.username=refset-prod
snowstorm.password=aandfhtlsfjh90F
snowstorm.authUrl=https://ims.ihtsdotools.org/api/
snowstorm.authHeader=Basic c25vd293bDpzbm93b3ds
snowstorm.baseUrl=https://snowstorm.ihtsdotools.org/snowstorm/snomed-ct/

# Search Handlers
search.handler=DEFAULT
search.handler.DEFAULT.class=org.ihtsdo.refsetservice.handler.DefaultSearchHandler

#
# Persistence Properties
#

# Spring JPA Configuration
#spring.h2.console.enabled=true

# Jpa-Hibernate Datasource Configuration
spring.jpa.properties.hibernate.hbm2ddl.auto=none
spring.jpa.properties.hibernate.connection.driver_class=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL94Dialect
spring.jpa.properties.hibernate.connection.url=jdbc:postgresql://localhost:5432/rt2
spring.jpa.properties.hibernate.connection.username=postgres
spring.jpa.properties.hibernate.connection.password=rootpwd
#spring.jpa.properties.hibernate.connection.driver_class=org.h2.Driver
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
#spring.jpa.properties.hibernate.connection.url=jdbc:h2:mem:test
#spring.jpa.properties.hibernate.connection.username=sa
#spring.jpa.properties.hibernate.connection.password=

# Jpa-Hibernate ORM Configuration
spring.jpa.properties.hibernate.archive.autodetection=class,hbm
spring.jpa.properties.hibernate.connection.useUnicode=true
spring.jpa.properties.hibernate.connection.characterEncoding=UTF-8
spring.jpa.properties.hibernate.connection.charSet=UTF-8
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=false
spring.jpa.properties.hibernate.jdbc.batch_size=5000
spring.jpa.properties.hibernate.jdbc.default_batch_fetch_size=320
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.jdbc.batch_versioned_data=true
spring.jpa.properties.hibernate.id.new_generator_mappings=true
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
#https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto-configure-hibernate-naming-strategy
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Elasticsearch Configuration
spring.jpa.properties.hibernate.search.default.indexmanager=directory-based
#spring.jpa.properties.hibernate.search.default.indexBase=${env:INDEX_BASE}
spring.jpa.properties.hibernate.search.default.indexBase=C:/index/data/rt2
spring.jpa.properties.hibernate.search.default.directory_provider=filesystem
spring.jpa.properties.hibernate.search.default.elasticsearch.host=http://127.0.0.1:9200
#spring.jpa.properties.hibernate.search.default.elasticsearch.path_prefix= n/a - only for deploy context path
spring.jpa.properties.hibernate.search.default.elasticsearch.username=elastic
spring.jpa.properties.hibernate.search.default.elasticsearch.password=changeme
spring.jpa.properties.hibernate.search.default.elasticsearch.index_schema_management_strategy=none
spring.jpa.properties.hibernate.search.default.elasticsearch.request_timeout=60000
spring.jpa.properties.hibernate.search.default.elasticsearch.connection_timeout=3000
spring.jpa.properties.hibernate.search.default.elasticsearch.read_timeout=60000
spring.jpa.properties.hibernate.search.default.elasticsearch.max_total_connection=20
spring.jpa.properties.hibernate.search.default.elasticsearch.max_total_connection_per_route=2
spring.jpa.properties.hibernate.search.default.elasticsearch.discovery.enabled=false
spring.jpa.properties.hibernate.search.default.elasticsearch.index_management_wait_timeout=10000
spring.jpa.properties.hibernate.search.default.elasticsearch.required_index_status=yellow
spring.jpa.properties.hibernate.search.default.elasticsearch.refresh_after_write=false
spring.jpa.properties.hibernate.search.elasticsearch.scroll_backtracking_window_size=1000
spring.jpa.properties.hibernate.search.elasticsearch.scroll_timeout=60
spring.jpa.properties.hibernate.search.default.elasticsearch.dynamic_mapping=strict
spring.jpa.properties.hibernate.search.elasticsearch.log.json_pretty_printing=true

# Flyway Configuration
spring.flyway.enabled=true
flyway.user=postgres
flyway.password=rootpwd
flyway.url=jdbc:postgresql://localhost:5432/rt2
#flyway.user=sa
#flyway.password=sa
#flyway.url=jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
flyway.locations=classpath:db/migration
spring.flyway.placeholders.pre_if_exists=
spring.flyway.placeholders.post_if_exists=if exists
spring.flyway.placeholders.create_mapping_events_seq=
spring.flyway.placeholders.auto_increment=BIGINT auto_increment
spring.flyway.placeholders.jsonb=text

# connection pooling
spring.jpa.properties.hibernate.connection.provider_class=org.hibernate.hikaricp.internal.HikariCPConnectionProvider
spring.jpa.properties.hibernate.hikari.minimumIdle=5
spring.jpa.properties.hibernate.hikari.maximumPoolSize=10
spring.jpa.properties.hibernate.hikari.idleTimeout=3600

